### ISSUE TITLE
None of these work?

### ISSUE THREAD

**Issue by zaqrkhan** [darshanbhatta/HumanBenchmarkBot#3]
Running the python files at 1920x1080 and bookmarks are off. And it says the game is not detected. How to fix this issue?

**Comment by darshanbhatta** [comment]
Hey, this project hasn't been updated in 3 years. I just recently cleaned up some of the old code but did not change the underlying bot. It looks like HumanBenchmark has changed the color of blue that they are using, which is why it's not working.

[Line to change I think](https://github.com/darshanbhatta/HumanBenchmarkBot/blob/master/ReactionTime.py#L25)

Instead of being #0089ce it looks like they are using #2b87d1 for the default background blue now. Feel free to create a pull request with it updated if you get it working, I am pretty sure that is the issue.

**Comment by longshishui** [comment]
> Hey, this project hasn't been updated in 3 years. I just recently cleaned up some of the old code but did not change the underlying bot. It looks like HumanBenchmark has changed the color of blue that they are using, which is why it's not working.
> 
> [Line to change I think](https://github.com/darshanbhatta/HumanBenchmarkBot/blob/master/ReactionTime.py#L25)
> 
> Instead of being #0089ce it looks like they are using #2b87d1 for the default background blue now. Feel free to create a pull request with it updated if you get it working, I am pretty sure that is the issue.

Yes, it works. And you also need to use #4bdb6a for the background green now.

**Comment by darshanbhatta** [comment]
> > Hey, this project hasn't been updated in 3 years. I just recently cleaned up some of the old code but did not change the underlying bot. It looks like HumanBenchmark has changed the color of blue that they are using, which is why it's not working.
> > [Line to change I think](https://github.com/darshanbhatta/HumanBenchmarkBot/blob/master/ReactionTime.py#L25)
> > Instead of being #0089ce it looks like they are using #2b87d1 for the default background blue now. Feel free to create a pull request with it updated if you get it working, I am pretty sure that is the issue.
> 
> Yes, it works. And you also need to use #4bdb6a for the background green now.

Aye, nice! Yeah please make a PR if you're able to so we can have it up to date.
